### ISSUE TITLE
need to make Lonnie shut up

### ISSUE THREAD

**Issue by lonniev** [API4KBs/api4kbs#13]

**Comment by RalphBln** [comment]
works for me ;)

**Comment by RalphBln** [comment]
Clarification: by works for me I mean Lonnie's activities are not an issue for me ;)

**Comment by lonniev** [comment]
“She”, the ontochatbot, will open new issues for us. You can see the syntax in my testing chatter with her:

github new issue “summary” for @user milestone # labels [ “foo” “bar” ] <<<WHY so we don’t have to duplicate our typing WHY

I’m hooking in the close issue handler now.

-- 
Lonnie VanZandt
303-900-3048

On 25 February 2016 at 10:27:56, Ralph Schäfermeier (notifications@github.com) wrote:

works for me ;)
