### ISSUE TITLE
Clarity in distinction between DOL and API4KB

### ISSUE THREAD

**Issue by lonniev** [API4KBs/api4kbs#32]
Reading the DOL spec and looking at the DOL ontology itself, it is clear what DOL is: an ontology for a distributed ontology language. Reading the LaTex API4KB, it is easy to get lost on what is API4KB because a large portion of that document speaks of what is DOL. This is confusing to a more general reader. If the confusion is more common than just a single instance of this reader (@lonniev) then document refactoring should be done to establish a more evident separation of concerns.

**Comment by lonniev** [comment]
@greenTara, there may be a more recent working copy of the API4KP draft. I am assuming that the link in #29 is our latest content. If I’m reading old materials, forgive me.

**Comment by greenTara** [comment]
Hi Lonnie - you should ignore everything in that draft after section 0. It
is full of DOL stuff because we started with the DOL draft as our template,
and then we are converting it to API4KB a little at a time. So far only
Section 0 has been modified, so everything after that is essentially some
draft of the DOL standard.

**Comment by lonniev** [comment]
Hi @lonniev - you should ignore everything in that draft after section 0. It is full of DOL stuff because we started with the DOL draft as our template, and then we are converting it to API4KB a little at a time. So far only Section 0 has been modified, so everything after that is essentially some draft of the DOL standard.

**Comment by lonniev** [comment]
@greenTara that is So Comforting to read: I was afraid you might reply that I was a silly twit who just didn’t get the big picture. (Not that you would so phrase it, of course.) Your explanation helps me a lot. I was spot on that the LaTex draft is an out of date precursor to the DOL spec. Cool. I rest in peace.
